export const ROLES = {
  SUPERADMIN: 1,
  ADMIN: 2,
  COMPANY_ADMIN: 3,
  BRANCH_MANAGER: 4,
  MANAGER: 5,
  MAINTENANCE: 6,
  DRIVER: 7,
  VIEWER: 8,
};

// For convenience, still group them
export const ROLE_GROUPS = {
  SYSTEM: [ROLES.SUPERADMIN, ROLES.ADMIN],
  COMPANY: [ROLES.COMPANY_ADMIN],
  BRANCH: [ROLES.BRANCH_MANAGER],
  OPERATIONS: [ROLES.MANAGER, ROLES.MAINTENANCE, ROLES.DRIVER],
  VIEW_ONLY: [ROLES.VIEWER],
};